ALTER TABLE [UserRole]
    ADD
    PeriodStart DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
    CONSTRAINT DF_UserRole_PeriodStart DEFAULT SYSUTCDATETIME(),
    PeriodEnd DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
    CONSTRAINT DF_UserRole_PeriodEnd DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    PERIOD FOR SYSTEM_TIME(PeriodStart, PeriodEnd),
    ChangedByIdentityId uniqueidentifier NOT NULL
	CONSTRAINT DF_ChangedByIdentityId_defaultvalue DEFAULT('00000000-0000-0000-0000-000000000000');
GO

ALTER TABLE UserRole
    SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.[UserRoleHistory]));
GO

ALTER TABLE [UserRole] DROP CONSTRAINT DF_ChangedByIdentityId_defaultvalue
GO