INSERT INTO [dbo].[GridArea] ([Id], [Code], [Name], [PriceAreaCode], [ValidFrom], [FullFlexDate], [ChangedByIdentityId])
VALUES
    (NEWID(), '065', 'Autogenerated for test', 1, '1990-01-01 23:00:00', '1990-01-01 23:00:00', '00000000-FFFF-FFFF-FFFF-000000000000'),
    (NEWID(), '028', 'Autogenerated for test', 1, '1990-01-01 23:00:00', '1990-01-01 23:00:00', '00000000-FFFF-FFFF-FFFF-000000000000'),
    (NEWID(), '098', 'Autogenerated for test', 1, '1990-01-01 23:00:00', '1990-01-01 23:00:00', '00000000-FFFF-FFFF-FFFF-000000000000'),
    (NEWID(), '105', 'Autogenerated for test', 1, '1990-01-01 23:00:00', '1990-01-01 23:00:00', '00000000-FFFF-FFFF-FFFF-000000000000'),
    (NEWID(), '080', 'Autogenerated for test', 1, '1990-01-01 23:00:00', '1990-01-01 23:00:00', '00000000-FFFF-FFFF-FFFF-000000000000'),
    (NEWID(), '070', 'Autogenerated for test', 1, '1990-01-01 23:00:00', '1990-01-01 23:00:00', '00000000-FFFF-FFFF-FFFF-000000000000'),
    (NEWID(), '067', 'Autogenerated for test', 1, '1990-01-01 23:00:00', '1990-01-01 23:00:00', '00000000-FFFF-FFFF-FFFF-000000000000'),
    (NEWID(), '021', 'Autogenerated for test', 1, '1990-01-01 23:00:00', '1990-01-01 23:00:00', '00000000-FFFF-FFFF-FFFF-000000000000'),
    (NEWID(), '053', 'Autogenerated for test', 1, '1990-01-01 23:00:00', '1990-01-01 23:00:00', '00000000-FFFF-FFFF-FFFF-000000000000'),
