INSERT INTO [dbo].[GridArea] ([Id], [Code], [Name], [PriceAreaCode], [ValidFrom], [FullFlexDate], [ChangedByIdentityId], [type])
VALUES
    (NEWID(), '113', 'Autogenerated for test', 1, '1990-01-01 23:00:00', '1990-01-01 23:00:00', '00000000-FFFF-FFFF-FFFF-000000000000', 2)