# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Continuous Integration of domain except for own NuGet packages
name: CI dotnet

on:
  workflow_call: {}

jobs:
  # Build all projects within solution
  dotnet_ci_build:
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-build-prerelease.yml@v14
    with:
      solution_file_path: source/marketparticipant/Energinet.DataHub.MarketParticipant.sln

  # Run all tests in 'Tests.dll'
  unit_test:
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-postbuild-test.yml@v14
    with:
      tests_dll_file_path: \source\marketparticipant\Energinet.DataHub.MarketParticipant.Tests\publish\Energinet.DataHub.MarketParticipant.Tests.dll
      download_attempt_limit: 18

  # Run tests in 'IntegrationTests.dll'
  integration_test:
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-postbuild-test.yml@v14
    with:
      tests_dll_file_path: \source\marketparticipant\Energinet.DataHub.MarketParticipant.IntegrationTests\publish\Energinet.DataHub.MarketParticipant.IntegrationTests.dll
      download_attempt_limit: 18
      use_azure_functions_tools: true
      environment: AzureAuth
      run_integration_tests: true
      azure_integrationtest_tenant_id: ${{ vars.integration_test_azure_tenant_id }}
      azure_integrationtest_subscription_id: ${{ vars.integration_test_azure_subscription_id }}
      azure_integrationtest_spn_id: ${{ vars.integration_test_azure_spn_id_oidc }}
      azure_keyvault_url: ${{ vars.integration_test_azure_keyvault_url }}
