name: CI orchestrator

on:
  pull_request:
    branches:
      - main
  merge_group:
    types: [checks_requested]

jobs:
  #
  # License and Markdown Check
  #
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@v14
    secrets:
      dh3serviceaccount_privatekey: ${{ secrets.dh3serviceaccount_privatekey }}

  #
  # Detect changes to start relevant workflows
  #
  changes:
    uses: ./.github/workflows/detect-changes.yml

  ci_dotnet:
    needs: changes
    if: ${{ needs.changes.outputs.dotnet == 'true' || needs.changes.outputs.db_migrations == 'true' }}
    uses: ./.github/workflows/ci-dotnet.yml

  ci_authorization_package:
    needs: changes
    if: ${{ needs.changes.outputs.ci_authorization_package == 'true' }}
    uses: ./.github/workflows/publish-market-participant-authorization-bundle.yml
    secrets: inherit

  render_c4model_views:
    needs: changes
    if: ${{ needs.changes.outputs.render_c4model_views == 'true' }}
    uses: Energinet-DataHub/.github/.github/workflows/structurizr-render-diagrams.yml@v14
    with:
      structurizr_workspace_filename: views
      included_model_filename: model
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  #
  # Branch policy status check
  #

  allow_merge_ci_orchestrator:
    runs-on: ubuntu-latest
    needs: [ci_base, ci_dotnet, ci_authorization_package, render_c4model_views]
    if: |
      always()
    steps:
      - name: Verify if merge is allowed
        run: |
          echo "${{ toJSON(needs) }}"

          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
              echo "Failed"
              exit 1
          fi
